{
  description = "Jonny's NixOS + Home Manager configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Rust toolchains as proper derivations (stable/beta/nightly), used by devShells.
    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Community hardware profiles: https://github.com/NixOS/nixos-hardware
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";

    # Pre-built Catppuccin theme modules for programs that have one.
    # Raw palette values come from lib/palette.nix instead.
    catppuccin.url = "github:catppuccin/nix";

    # Secrets encrypted in-repo, decrypted at activation. See .sops.yaml.
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, fenix, catppuccin, ... }@inputs:
    let
      system = "x86_64-linux";

      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      pkgsWithFenix = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
        overlays = [ fenix.overlays.default ];
      };
    in
    {
      # ---- optiplex: Dell OptiPlex desktop (Intel, Sway) ----
      # A single `nixos-rebuild switch` handles both system and user config.
      nixosConfigurations."optiplex" = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs; };
        modules = [
          ./modules/nixos
          ./hosts/optiplex

          home-manager.nixosModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              extraSpecialArgs = { inherit inputs; };
              users.jonny.imports = [
                catppuccin.homeModules.catppuccin
                ./modules/home
                ./hosts/optiplex/home.nix
              ];
            };
          }
        ];
      };

      # Per-stack dev environments: `nix develop .#ruby`, or per-project via
      # `echo "use flake ~/git/nix#ruby" > .envrc && direnv allow`.
      devShells.${system} = import ./devshells { inherit pkgs pkgsWithFenix; };

      formatter.${system} = pkgs.nixpkgs-fmt;

      # `nix flake check` builds the system closure (via nixosConfigurations)
      # and additionally lints the tree, so a dead binding or an anti-pattern
      # fails CI rather than lingering.
      checks.${system} = {
        statix = pkgs.runCommand "statix-check" { nativeBuildInputs = [ pkgs.statix ]; } ''
          # hosts/*/hardware.nix is generated; not ours to restyle.
          statix check --ignore hardware.nix ${self} && touch $out
        '';

        deadnix = pkgs.runCommand "deadnix-check" { nativeBuildInputs = [ pkgs.deadnix ]; } ''
          # hosts/*/hardware.nix is generated by nixos-generate-config; its unused
          # module arguments are not ours to fix.
          deadnix --fail --exclude ${self}/hosts/optiplex/hardware.nix ${self} && touch $out
        '';
      };
    };
}
