# ============================================================
# Hardware configuration — mac
# ============================================================
# This file is generated by nixos-generate-config on the target machine.
#
# To generate it during install:
#   nixos-generate-config --show-hardware-config > /mnt/etc/nixos/hardware.nix
#   cp /mnt/etc/nixos/hardware.nix ~/git/nix/hosts/mac/hardware.nix
#
# Or after first boot:
#   nixos-generate-config --show-hardware-config > ~/git/nix/hosts/mac/hardware.nix
#
# Do NOT hand-edit this file — regenerate it if hardware changes.
# ============================================================

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Replace everything below with the output of nixos-generate-config.
  # The placeholders here will fail to build intentionally.

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules          = [ ];
  boot.kernelModules                 = [ "kvm-intel" ];
  boot.extraModulePackages           = [ ];

  # ── Filesystems ────────────────────────────────────────────
  # Replace these with your actual partition UUIDs from blkid.
  # Example (adjust to your partition layout):
  #
  #   fileSystems."/" = {
  #     device = "/dev/disk/by-uuid/XXXX-XXXX";
  #     fsType = "ext4";
  #   };
  #
  #   fileSystems."/boot" = {
  #     device = "/dev/disk/by-uuid/XXXX-XXXX";
  #     fsType = "vfat";
  #   };
  #
  #   swapDevices = [
  #     { device = "/dev/disk/by-uuid/XXXX-XXXX"; }
  #   ];

  fileSystems."/" = {
    device = "REPLACE_WITH_ROOT_UUID";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "REPLACE_WITH_BOOT_UUID";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # ── Platform ───────────────────────────────────────────────
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
