{ config, lib, pkgs, ... }:

# Experimental alternative to waybar + rofi + mako, switched on with
# jonny.desktop.shell = "quickshell" (see the option in ../default.nix).
# waybar.nix, rofi.nix and mako.nix are untouched by this file — waybar and
# mako just gate their own `config` on the same option (one line each) so
# the two shells never fight over the top bar or the notification bus name.
# rofi stays enabled either way: half the scripts in scripts.nix use it as a
# plain dmenu picker, unrelated to which shell owns the app launcher.
#
# Everything here reads jonny.theme.palette and jonny.desktop.scripts the
# same way waybar does, so switching shells is a look, not a rebuild of what
# either one can do.
let
  cfg = config.jonny.desktop;
  p = config.jonny.theme.palette;
  fonts = config.jonny.theme.fonts;

  # Every semantic colour + geometry constant the QML tree reads from,
  # regenerated from the active scheme on every switch. Keep this in sync
  # with qml/Common/Theme.qml's property list — that file is the local-dev
  # placeholder `quickshell -p qml` runs against without Nix.
  themeQml = pkgs.writeText "Theme.qml" ''
    pragma Singleton
    import QtQuick

    // Generated by modules/home/desktop/quickshell/default.nix from
    // jonny.theme.palette — do not edit by hand, edit lib/schemes/ instead.
    QtObject {
        readonly property color bg: "${p.bg}"
        readonly property color bgAlt: "${p.bgAlt}"
        readonly property color bgInset: "${p.bgInset}"
        readonly property color surface: "${p.surface}"
        readonly property color surfaceAlt: "${p.surfaceAlt}"
        readonly property color surfaceActive: "${p.surfaceActive}"
        readonly property color fg: "${p.fg}"
        readonly property color fgMuted: "${p.fgMuted}"
        readonly property color fgDim: "${p.fgDim}"
        readonly property color fgSubtle: "${p.fgSubtle}"
        readonly property color border: "${p.border}"
        readonly property color borderActive: "${p.borderActive}"
        readonly property color highlight: "${p.highlight}"
        readonly property color accent: "${p.accent}"
        readonly property color error: "${p.error}"
        readonly property color warning: "${p.warning}"
        readonly property color success: "${p.success}"
        readonly property color info: "${p.info}"

        readonly property QtObject hues: QtObject {
            readonly property color red: "${p.hues.red}"
            readonly property color orange: "${p.hues.orange}"
            readonly property color yellow: "${p.hues.yellow}"
            readonly property color green: "${p.hues.green}"
            readonly property color cyan: "${p.hues.cyan}"
            readonly property color blue: "${p.hues.blue}"
            readonly property color purple: "${p.hues.purple}"
            readonly property color magenta: "${p.hues.magenta}"
        }

        // Qt substitutes missing glyphs (the Nerd Font icons this family
        // doesn't have) from the system fontconfig fallback chain
        // automatically, so a single family name is enough here.
        readonly property string fontFamily: "${fonts.ui.family}"
        readonly property int fontSize: ${toString fonts.ui.size}

        readonly property int radius: 20
        readonly property int radiusSmall: 12
        readonly property int barHeight: 40
        readonly property int gap: 8

        readonly property int animFast: 120
        readonly property int animMed: 220
        readonly property int animSlow: 400
        readonly property int animBounce: 550
    }
  '';

  # The static QML tree plus the generated theme, combined into one config
  # directory for home-manager's `programs.quickshell.configs`.
  quickshellConfig = pkgs.runCommand "quickshell-jonny-config" { } ''
    mkdir -p "$out"
    cp -r ${./qml}/. "$out/"
    chmod -R u+w "$out"
    cp ${themeQml} "$out/Common/Theme.qml"
  '';

  listApps = pkgs.writers.writePython3Bin "quickshell-list-apps" { } (
    builtins.readFile ./scripts/list-apps.py
  );

  # Mirrors waybar's built-in `network` module (modules/home/desktop/
  # waybar.nix) so the two bars show the same thing — nmcli rather than
  # netlink directly, since this only needs to be polled every few seconds
  # rather than pushed.
  networkStatus = pkgs.writeShellApplication {
    name = "quickshell-network-status";
    runtimeInputs = with pkgs; [ networkmanager jq gawk ];
    text = ''
      active=$(nmcli -t -f TYPE,STATE,CONNECTION device status 2>/dev/null \
        | awk -F: '$2=="connected"{print $1"|"$3; exit}')

      if [ -z "$active" ]; then
        jq -c -n '{icon:"󰤭", state:"disconnected", tooltip:"Disconnected"}'
        exit 0
      fi

      type=''${active%%|*}
      conn=''${active#*|}

      case "$type" in
        wifi)
          signal=$(nmcli -t -f active,signal dev wifi 2>/dev/null \
            | awk -F: '$1=="yes"{print $2; exit}')
          signal=''${signal:-0}
          icon="󰤯"
          if   [ "$signal" -ge 80 ]; then icon="󰤨"
          elif [ "$signal" -ge 60 ]; then icon="󰤥"
          elif [ "$signal" -ge 40 ]; then icon="󰤢"
          elif [ "$signal" -ge 20 ]; then icon="󰤟"
          fi
          jq -c -n --arg icon "$icon" --arg conn "$conn" --arg signal "$signal" \
            '{icon:$icon, state:"wifi", tooltip:($conn+" · "+$signal+"%")}'
          ;;
        ethernet)
          jq -c -n --arg conn "$conn" '{icon:"󰈀", state:"ethernet", tooltip:$conn}'
          ;;
        *)
          jq -c -n --arg conn "$conn" '{icon:"󰈀", state:"other", tooltip:$conn}'
          ;;
      esac
    '';
  };
in
{
  config = lib.mkIf (cfg.enable && cfg.shell == "quickshell") {
    home.packages = [ listApps networkStatus ];

    programs.quickshell = {
      enable = true;
      configs.jonny = quickshellConfig;
      activeConfig = "jonny";
      systemd = {
        enable = true;
        target = cfg.sessionTarget;
      };
    };
  };
}
