# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-335c42eb-1da8-43f2-a271-5caa94b81c57";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-335c42eb-1da8-43f2-a271-5caa94b81c57".device = "/dev/disk/by-uuid/335c42eb-1da8-43f2-a271-5caa94b81c57";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4569-4B51";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3f374acb-7aaf-4c5d-9b48-fac6c449931f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
